export const endpoints = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    changePassword: "/auth/change-password",
    me: "/auth/me",
    twoFactorSetup: "/auth/2fa/setup",
    twoFactorSetupAuthenticated: "/auth/2fa/setup-authenticated",
    twoFactorConfirm: "/auth/2fa/confirm",
    twoFactorDisable: "/auth/2fa/disable",
  },
  dashboard: {
    summary: "/dashboard",
    transactionTrend: "/dashboard/transaction-trend",
    assetDistribution: "/dashboard/asset-distribution",
    recentActivity: "/dashboard/recent-activity",
    systemAlerts: "/alerts",
    transactionVolume7d: "/transactions/volume-7d",
  },
  walletCenter: {
    summary: "/wallets/summary",
    wallets: "/wallets",
    detail: (address: string) => `/wallets/${address}`,
    export: "/wallets/export",
  },
  userCenter: {
    summary: "/user-center/summary",
    devices: "/devices",
  },
  transactions: {
    summary: "/transactions/summary",
    volume24h: "/transactions/volume-24h",
    volume7d: "/transactions/volume-7d",
    list: "/transactions",
  },
  system: {
    status: "/system/status",
    chains: "/system/chains",
    services: "/system/services",
    logs: "/system/logs",
  },
  admin: {
    roles: "/roles",
    role: (id: number) => `/roles/${id}`,
    rolePermissions: (id: number) => `/roles/${id}/permissions`,
    permissions: "/permissions",
    summary: "/admins/summary",
    list: "/admins",
    create: "/admins",
    update: (id: number) => `/admins/${id}`,
    updateStatus: (id: number) => `/admins/${id}/status`,
    delete: (id: number) => `/admins/${id}`,
  },
  alerts: {
    list: "/alerts",
    resolve: (id: string) => `/alerts/${id}/resolve`,
  },
  dapps: {
    summary: "/dapps/summary",
    list: "/dapps",
    create: "/dapps",
    update: (id: number) => `/dapps/${id}`,
    delete: (id: number) => `/dapps/${id}`,
    types: "/dapp-types",
    categories: "/dapp/types",
    category: (id: number) => `/dapp/types/${id}`,
  },
  tronGas: {
    overview: "/tron-gas/overview",
    config: "/tron-gas/config",
    nettsConsumptionExport: "/tron-gas/netts-consumption/export",
    nettsAccountSync: "/tron-gas/netts-account/sync",
  },
} as const;
